#ifndef __WT_BUILD_H_
#define __WT_BUILD_H_
#define WT_BUILD_YEAR_4 2
#define WT_BUILD_YEAR_3 0
#define WT_BUILD_YEAR_2 2
#define WT_BUILD_YEAR_1 4
#define WT_BUILD_MONTH_2 0
#define WT_BUILD_MONTH_1 6
#define WT_BUILD_DAY_2 1
#define WT_BUILD_DAY_1 1
#define WT_BUILD_HOUR_2 1
#define WT_BUILD_HOUR_1 5
#define WT_BUILD_MINUTE_2 3
#define WT_BUILD_MINUTE_1 8
#define WT_BUILD_SECOND_2 0
#define WT_BUILD_SECOND_1 4

#define WT_BUILD_VERSION_MAJOR 1
#define WT_BUILD_VERSION_MINOR 0
#define WT_BUILD_VERSION_PATCH 5
#endif
